---
title: "Medicine"
author: "Susmit"
date: "`r Sys.Date()`"
documentclass: memoir
output: pdf_document
fontsize: 12pt
geometry: margin=2cm
---

\openany
\raggedbottom
\twocoltocetc
\tableofcontents

\pagebreak


# Cardiology
## Presenting problems in CVS disease
### Features of benign murmur
- Soft
- Midsystolic
- Heard at left sternal edge
- No radiation
- No other cardiac abnormalities

\pagebreak

# Dermatology
## Anatomy and physiology
- Layers of skin:
	- Epidermis: further layered into (from out$\rightarrow$in)
		- corneum
		- lucidum
		- granulosum
		- spinosum
		- basale
	- Dermis: contains
		- blood vessels
		- nerves
		- pilosebaceous units (hair follicle + sebaceous gland)
	- Subcutis: adipose

### Epidermal appendages
- Hair follicles:
	- phases of growth
		- anagen: 
			- active growth
			- lasts years in scalp hairs
		- catagen: 
			- transitional
			- lasts days (in scalp)
		- telogen: 
			- resting
			- lasts months (in scalp)
- Sebaceous glands
	- usually _associated with a hair follicle_
	- $\fbox{androgens}\rightarrow$ **$\uparrow$** $\fbox{sebum}$
	- $\fbox{oestrogen}\rightarrow$ **$\downarrow$** $\fbox{sebum}$
- Sweat glands
	- innerved by _sympathetic cholinergic_ fibres

## Principles of management of skin disease
### Topical treatments
- Ointments vs Creams
	- Ointments preferred to creams for dry skin (e.g. chronic eczema) as
		- more hydrating
			- 80% oil + 20% water in ointments (vs 50-50 for creams) $\rightarrow$
		 	prevent water loss from skin by oil layer
		- less preservatives $\rightarrow$ less risk of allergy
- Emollients
	- Moisturise, lubricate, protect skin
	- _Vehicles without active drug_
- Gluocorticoids

### Phototherapy
- **UVB**
- **Psoralen UVA**
	- Psoralen:
		- natural photosensitiser from plant source
		- cross-link DNA strands on excitation with UVA
	- Cumulative exposure to PUVA $\rightarrow\;\;\uparrow$
	 risk of SCC, so reserved for UVB resistance
- Uses
	- Psoriasis
	- Atopic eczema
	- Vitiligo
	- Chronic urticaria

### Systemics
- Antihistamines
- **Retinoids**
	- _Anti-inflammatory_
	- Promote _differentiation of skin cells_
	- **Teratogenic**
		- must be prescribed with robust contraception
		- females must have negative pregnancy test before, during, and after
		 therapy
- **Immunosuppressants**
	- Glucocorticoids e.g. prednisolone
	- Methotrexate
	- Azathioprine

### Biologics
- Biological _inhibitors_ of _proinflammatory cytokines_
- **TNF-$\alpha$ inhibitors**
	- Infliximab
	- Etanercept
- **Interleukin inhibitors**
	- Ustekinumab: IL-12, 23
	- Guselkumab: IL-23
	- Secukinumab: IL-17
- _Rituximab_:
	- Binds to CD20 $\rightarrow$ cause ADCC of B cells
	- As terminally differentiated plasma cells don't have CD20 they're safe
	- Use: pemphigus vulgaris

### Non-surgical therapy
- **Cryo**
	- _Liquid N$_2$_
	- Causes cell membrane destruction $\rightarrow$ death
- Laser

## Skin cancers
### Classification
- Non-melanoma skin cancer (NMSC): most common
	- SCC
	- BCC
- Melanoma
	- Less common
	- More metastatic risk $\rightarrow$ cause of most skin cancer deaths


## Fungal infections
### Types
- Superficial
	- Dermatophytes: aka **ringworm / tineasis**
		- _Trichophyton_
		- _Epidermophyton_
		- _Microsporum_
			
	- Yeast
- Deep: less common
	- Chromomycosis
	- Sporotrichosis



## Scabies
### Agent
Caused by the mite _Sarcoptis scabies hominis_

### Diagnosis
- Identify the skin burrow 
- Visualize the mite by dermatoscope / extracting with a needle

### Treatment
- Affected + all asymptomatic family members / physical contacts
- Topical permethrin / malathion
	- 2 applications
	- 1 wk apart
	- Whole body, except head
- Oral Ivermectin:
	- Single dose
	- For poor adherence, immunosuppresion or heavy infestation


## Pseudorandom factoids
### SPF (sun protection factor)
- $\frac{\LARGE{\text{UV dose for producing erythema with sunscreen}}}
{\LARGE{\text{UV dose for producing erythema without sunscreen}}}$

### Mechanism of venous ulceration
\begin{center}
\fbox{Incompetent valves} \\
$\downarrow$ \\
\fbox{$\uparrow$ capillary pressure} \\
$\downarrow$ \\
\fbox{Fibrinogen leaks out of capillary} \\
$\downarrow$ \\
\fbox{Forms fibrin clot around capillary (pericapillary cuffing)} \\
$\downarrow$ \\
\fbox{Impaired diffusion from capillaries} \\
$\downarrow$ \\
\fbox{Impaired oxygenation}
\end{center}


\pagebreak


# Neurology
## Raised ICP
- Normal ICP = **5-15 mmHg**

### Causes
- **ICSOL**
	- Intracranial haemorrhage
	- Tumours e.g. glioma
	- Brain abscess
- **Hydrocephalus**: blockade of CSF circulation
	- Obstructive / non-communicating
	- Communicating
- **Cerebral oedema** e.g. meningoencephilitis
- **Venous sinus obstruction** e.g. cerebral venous thrombosis

### Features
- **Headache**
- **Vomiting**
- **Diplopia / blurred vision**: Due to _6th nerve palsy_
	- 6th nerve palsy due to
		- stretching of the long, slender nerve
		- compression against petrous temporal bone
- **Papilloedema**
- **Bradycardia**
- **Hypertension**
- **Depressed consciousness**

### Management
- According to cause:
	- Mass lesion $\rightarrow$ surgical decompression
	- Hydrocephalus $\rightarrow$ _ventriculoperitoneal shunt_ operation
	- Oedema $\rightarrow$ glucocorticoids
- Supportive:
	- Head elevation
	- Fluid balance
	- BP control
	- Diuretics: mannitol
