graph TB
    A[Bladder filled with some urine]
    -->B[Raised pressure in the bladder wall]
    -->C[Firing of stretch receptors]
    -->D["Signal goes to S2-4 via <br/>pelvic splanchnic afferents"]
    -->E["Reflex firing of sympathetic<br/> efferents from hypogastric nerve"]
    -->F["Relaxation of detrusor<br/>Contraction of internal sphincter"]
    -->G["No micturition"]
