graph TB
	subgraph "Minimal change disease"
		A[Immune-mediated<br/> destruction of <br/>podocyte foot processes]
    	-->B[Larger filtration pores]
    	C[Loss of glomerular<br/>polyanions]
    	-->D[Loss of repulsion<br/>of proteins by the<br/>glomerulus]
    	B & D --> E[Protein leakage]
	end

	subgraph "Membranous nephropathy"
        direction TB
        F["Deposition of immune<br>complexes (e.g. in SLE)"]
        G["Binding of auto-antibodies<br> to renal auto-antigens<br>(e.g. in primary MN)"]
        F & G --> H["Complement activation<br>Membrane attack complex<br>formation"]
        -->I["Injury to the capillary wall"]
        -->J["Protein leakage"]
    end
