graph TB
title[<h1>Treatment of psoriasis</h1>]
title-->A[Advice, education, support]
style title fill:#FFF,stroke:#FFF,color:#000
linkStyle 0 stroke:#FFF,stroke-width:0;

A-->B[<b>Topicals</b>: emollients, vitamin D analogues, retinoids, glucocorticoids<br/>]
B-->C[<b>Phototherapy</b>: narrowband UVB, PUVA]
C-->D[<b>Immunosuppressants</b>:<br/> methotrexate, ciclosporin]
C-->E[<b>Systemic retinoids</b>: acitretin]

D-->F[Fumaric acid esters/apremilast]
E-->F
F-->G[<b>Severely resistant disease:</b><br/> <b>biologics</b>]
G-->H[<b>Anti-TNF-α</b><br/>Infliximab, Etanercept,<br/> Adalimumab]
G-->I[<b>Anti-IL-12/23</b><br/>Ustekinumab]
G-->J[<b>Anti-IL-23</b><br/>Guselkumab]
