graph TB
    a[CKD]-->b[<b>Failure of <br>PO4 excretion]
    a-->c[<b>Failure of<br>Vit-D activation]
    b-->d[Rise in serum PO4]
    d-->e[FGF23 secreted<br>from osteocytes]
    d-->f["PTH secretion<br>from parathyroid<br>(<b>2◦ hyperparathyroidism</b>)<br>Parathyroid hyperplasia"]
    e & f-->g[Excretion of PO4]
    c-->h[Impaired Ca absorption<br>in gut]-->i[<b>Hypo-Ca]-->f-->j[<b>Bone resorption</b><br>to mobilise Ca from<br>bone]
