graph LR
  a[<b>AGEs</b>]-->b[Bind to RAGEs]
  b-->c[Release growth factors<br>and cytokines, e.g.<br><b>TGF-β, VEGF]
  b-->g[Proliferation of vascular<br> smooth muscle cells<br> and synthesis of<br> extracellular matrix]
  g & c -->d[<b>Basement membrane<br>thickening</b>]

  b-->e["↑<b>Reactive O<sub>2</sub> species</b><br>(ROS) production by<br>endothelial cells"]
  b-->f["↑Procoagulant activity<br>on endothelial cells"]
  a-->i[Directly cross-link<br>type IV collagen in<br>basement membrane]
  -->j["↓Endothelial cell<br>adhesion"]
  -->k["Fluid extravasation"]
  i-->l[<b>Trap nonglycated<br>proteins e.g. LDL]
  -->m["↑Atherogenesis"]
