graph TB
title[<h1>Treatment of eczema</h1>]
title-->A[Advice, education, support]
style title fill:#FFF,stroke:#FFF
linkStyle 0 stroke:#FFF,stroke-width:0;

A-->B[<b>Topicals</b>: emollients, glucocorticoids, calcineurin inhibitors<br/><br/> Sedating antihistamines: if sleep is interrupted]
B-->C[<b>Phototherapy</b>: narrowband UVB, PUVA]
C-->D[<b>Immunosuppressants</b>: prednisolone, methotrexate]
C-->E[<b>Systemic retinoids</b>: acitretin]
D-->F[<b>Severely resistant disease</b>: biologics e.g. <b>dupilumab</b>]
E-->F
