graph TB
    G[Bladder fully filled]
    -->H[Higher amplitude stretch signals]
    -->I[Signals go to pontine<br/>micturition centre]
    -->J[Awareness of filled bladder]
    J-->|Want to void|K[Pontine signals<br/>inhibit hypogastric and<br/>pudendal efferents]
    -->L[Detrusor contracts<br/>Internal sphincter relaxes<br/>External sphincter relaxes]
    J-->|Don't want to void|M[No inhibition of<br/>hypogastric and<br/> pudendal efferents]
    -->N[No micturition]

