graph TB
    a[PTH]-->b["<b>Binds to osteo<i>blasts</i></b><br>(clasts don't have PTH<br>receptor)"]
    b-->c[<b>Increased RANKL</b><br>expression on<br>blast surface] & d["<b>Decreased OPG</b><br>(osteoprotegerin)<br>secretion by blast"]
    c-->e["Bind to RANK on<br>clast precursors<br>(<b>RANKL-RANK <br>interaction</b>)"]
    d-->f[Reduced binding of<br>RANKL with OPG]-->i[Reduced inhibition of<br>RANKL-RANK]
    e & i-->g[Maturation of osteoclasts]-->h[Bone resorption]
