graph TB
A[Bacterial endotoxin]-->B[macrophage activation]
B-->C[IL-2, 6, TNF]
C-->D[neutrophil activation]
D-->E[release of further inflammatory mediators]
E-->M[nitric oxide]-->F[vasodilation]
F-->K[hypotension]
E-->N[endothelial injury]
N-->I[coagulation cascade activation]
I-->J[DIC]
K-->L[multi organ failure]
J-->L
