graph TB
A[<b>Airway</b> maintenance<br/>Left lateral <b>position</b><br/><b>O<sub>2</sub></b> to prevent cerebral hypoxia<br/>Check <b>pulse, resp rate, BP, glucose</li></ul]-->|"Seizure continued for <b>> 5mins"|B["<b>Diazepam 10mg PR</b><br/>(or IV if necessary)"]
B-->|Seizure continued for <b>> 15mins|B
B-->|Seizure continued for <b>> 30 mins</b>|C["<b>IV phenytoin 15 mg/kg<br/></b>Alternatives: Na-valproate,<br/>Phenobarbital"]
C-->|"Seizure continued for > 60mins"|D["Transfer to ICU"]
